[project]
requires-python = ">=3.10"

[tool.ruff]
line-length = 98

[tool.ruff.lint]
select = [
    "W",
    "E",
    "F",
    "I", 
    "N",
    "DJ",
    "T20",
    "Q"
]

fixable = [ "I" ] #импорты

ignore = [ "T201" ]


